### ISSUE TITLE
Consistency graph is built based on both training and test dataset? wondering if it is the main reason the method works well for unseen scenarios?

### ISSUE THREAD

**Issue by hailingzhou** [yeliudev/ConsNet#10]
Technically, it is not totally unseen scenarios because consistency graph already has both visual and semantic features from training and testing datasets. I don't know if I understand correctly?

**Comment by yeliudev** [comment]
Thanks for your question! According to our experiments, it does not matter whether the consistency graph is built based on the `train` or `train + test` split, since the samples are only used to cluster 'general' visual representations of nodes. You may try to use the `train` split only, and the performances are expected to be the same.
